-- Categories
INSERT INTO texts (default_text) VALUES ('Featured');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'FEATURED',0,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Featured');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Destacados');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','En vedette');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Vorgestellt');
INSERT INTO texts (default_text) VALUES ('Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'TOP',1,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Top');
INSERT INTO texts (default_text) VALUES ('Location');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'LOCATION',2,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Location');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Ubicación');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Emplacement');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Lage');
INSERT INTO texts (default_text) VALUES ('Friends');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'FRIENDS',3,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Friends');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Amigos');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Amis');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Freunde');
INSERT INTO texts (default_text) VALUES ('Art');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'ART',4,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Art');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Arte');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Art');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Kunst');
INSERT INTO texts (default_text) VALUES ('Comics');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'COMICS',5,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Comics');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Historietas');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Bandes dessinées');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Comics');
INSERT INTO texts (default_text) VALUES ('Dance');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'DANCE',6,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Dance');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Danza');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Danse');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','tanzen');
INSERT INTO texts (default_text) VALUES ('Design');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'DESIGN',7,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Design');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Diseño');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Conception');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Entwurf');
INSERT INTO texts (default_text) VALUES ('Fashion');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'FASHION',8,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Fashion');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Moda');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Mode');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Mode');
INSERT INTO texts (default_text) VALUES ('Movies');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'MOVIES',9,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Movies');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Hombre moviente');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Films');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Kino');
INSERT INTO texts (default_text) VALUES ('Food');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'FOOD',10,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Food');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Comida');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Nourriture');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Lebensmittel');
INSERT INTO texts (default_text) VALUES ('Games');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'GAMES',11,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Games');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Juegos');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Jeux');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Spiele');
INSERT INTO texts (default_text) VALUES ('Music');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'MUSIC',12,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Music');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Música');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Musique');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Musik');
INSERT INTO texts (default_text) VALUES ('Publishing');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'PUBLISHING',13,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Publishing');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Publicación');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','édition');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Verlagswesen');
INSERT INTO texts (default_text) VALUES ('Theater');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'THEATER',14,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Theater');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Teatro');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Théâtre');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Schauplatz');
INSERT INTO texts (default_text) VALUES ('Software');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'SOFTWARE',15,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Software');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Software');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Logiciel');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Software');
INSERT INTO texts (default_text) VALUES ('Housing');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'HOUSING',16,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Housing');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Alojamiento');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Logement');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Wohnungsbau');
INSERT INTO texts (default_text) VALUES ('Technology');
SET @lastid = LAST_INSERT_ID();
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'TECHNOLOGY',17,null);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Technology');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','tecnología');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','technologie');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Technologie');
INSERT INTO texts (default_text) VALUES ('Games');
SET @lastid = LAST_INSERT_ID();
SET @parentid := (SELECT c.id FROM categories c WHERE c.code = 'SOFTWARE');
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'SOFTWARE_GAMES',0,@parentid);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Games');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Juegos');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Jeux');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Spiele');
INSERT INTO texts (default_text) VALUES ('Applications');
SET @lastid = LAST_INSERT_ID();
SET @parentid := (SELECT c.id FROM categories c WHERE c.code = 'SOFTWARE');
INSERT INTO categories (name_id,code,sort_order,parent_id) VALUES (@lastid,'SOFTWARE_APPLICATIONS',1,@parentid);
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Applications');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Aplicaciones');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'fr','Applications');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'de','Anwendungen');
