
INSERT INTO texts (default_text) VALUES ('Default Public Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Public Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú predeterminado a la derecha');
INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('PUBLIC_MENU_RIGHT','PUBLIC',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_HOME','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_RIGHT'),'Home','/','fa fa-home fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_RIGHT'),'Casa','/','fa fa-home fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_SERVICES','SERVICES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Services','/services','fa fa-cloud fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Servicios','/services','fa fa-cloud fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_ABOUT','ABOUT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'About','/about','fa fa-question-circle fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'Acerca de','/about','fa fa-question-circle fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_LOGIN','LOGIN',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Login','/login','fa fa-sign-in fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Iniciar sesión','/login','fa fa-sign-in fa-1','es',true);

-- Private menu
INSERT INTO texts (default_text) VALUES ('Default Member Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Member Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú miembro de Izquierda');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_MENU_LEFT','MEMBER',@lastid,'1.0','1.0');
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_HOME','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_LEFT'),'Home','/member/social/index.html','en',true);

-- Social
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_SOCIAL','SOCIAL',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Social','','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Medios de Comunicación Social','','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_ACQUAINTANCE','ACQUAINTANCE',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Acquaintances','/member/social/index.html?page=acquaintance','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Conocidos','/member/social/index.html?page=acquaintance&lang=es','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_GROUPS','GROUPS',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Groups','/member/social/index.html?page=groups','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Grupos','/member/social/index.html?page=groups&lang=es','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_ACTIVITIES','ACTIVITIES',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Activities','/member/social/index.html?page=activities','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Actividades','/member/social/index.html?page=activities&lang=es','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_EVENTS','EVENTS',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Events','/member/social/index.html?page=events','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Eventos','/member/social/index.html?page=events&lang=es','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_MESSAGES','MESSAGES',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Messages','/member/social/index.html?page=messages','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Mensajes','/member/social/index.html?page=messages&lang=es','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_LIBRARY','LIBRARY',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Library','/member/social/index.html?page=library','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Biblioteca','/member/social/index.html?page=library&lang=es','es',true);

INSERT INTO texts (default_text) VALUES ('Member Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Member Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú de miembros Arriba');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_MENU_TOP','MEMBER',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Home','/member','fa fa-home fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Casa','/member','fa fa-home fa-1','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MPM','PM',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'Gate Dog','/pm-gatedog','fa fa-bug fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'Gate Dog','/pm-gatedog','fa fa-bug fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMTEAM','PM_TEAM',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TEAM' and menus.code = 'MEMBER_MENU_TOP'),'Team','/pm-team','fa fa-columns fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TEAM' and menus.code = 'MEMBER_MENU_TOP'),'Equipo','/pm-team','fa fa-columns fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMPROD','PM_PRODUCT',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PRODUCT' and menus.code = 'MEMBER_MENU_TOP'),'Product','/pm-product','fa fa-columns fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PRODUCT' and menus.code = 'MEMBER_MENU_TOP'),'Producto','/pm-product','fa fa-columns fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMPROJ','PM_PROJECT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PROJECT' and menus.code = 'MEMBER_MENU_TOP'),'Project','/pm-project','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PROJECT' and menus.code = 'MEMBER_MENU_TOP'),'Proyecto','/pm-project','fa fa-list fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMREL','PM_RELEASE',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_RELEASE' and menus.code = 'MEMBER_MENU_TOP'),'Release','/pm-release','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_RELEASE' and menus.code = 'MEMBER_MENU_TOP'),'Lanzamiento','/pm-release','fa fa-list fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMBAK','PM_BACKLOG',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_BACKLOG' and menus.code = 'MEMBER_MENU_TOP'),'Backlog','/pm-backlog','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_BACKLOG' and menus.code = 'MEMBER_MENU_TOP'),'Reserva','/pm-backlog','fa fa-list fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMDEF','PM_DEFECT',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEFECT' and menus.code = 'MEMBER_MENU_TOP'),'Defect','/pm-defect','fa fa-columns fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEFECT' and menus.code = 'MEMBER_MENU_TOP'),'Defecto','/pm-defect','fa fa-columns fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMENH','PM_ENHANCMENT',6);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_ENHANCMENT' and menus.code = 'MEMBER_MENU_TOP'),'Enhancement','/pm-enhancement','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_ENHANCMENT' and menus.code = 'MEMBER_MENU_TOP'),'Mejora','/pm-enhancement','fa fa-list fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMTASK','PM_TASK',7);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TASK' and menus.code = 'MEMBER_MENU_TOP'),'Task','/pm-task','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TASK' and menus.code = 'MEMBER_MENU_TOP'),'Tarea','/pm-task','fa fa-list fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMWF','PM_WORKFLOW',8);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_WORKFLOW' and menus.code = 'MEMBER_MENU_TOP'),'Workflow','/pm-workflow','fa fa-list fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_WORKFLOW' and menus.code = 'MEMBER_MENU_TOP'),'Flujo de trabajo','/pm-workflow','fa fa-list fa-1','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MA','ACQUAINTANCE',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Acquaintances','/member-acquaintances','fa fa-user-plus fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Conocidos','/member-acquaintances','fa fa-user-plus fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MG','GROUPS',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Groups','/member-groups','fa fa-users fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Grupos','/member-groups','fa fa-users fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MS','SHOP',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SHOP' and menus.code = 'MEMBER_MENU_TOP'),'Shop','/member-shopping','fa fa-cart-arrow-down fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SHOP' and menus.code = 'MEMBER_MENU_TOP'),'Tienda','/member-shopping','fa fa-cart-arrow-down fa-1','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MN','NOTES',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notes','/member-notes','fa fa-sticky-note fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notas','/member-notes','fa fa-sticky-note fa-1','es',true);

-- user profile
INSERT INTO texts (default_text) VALUES ('Member Profile Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Member Profile Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Parte superior del menú de perfil de miembro');
INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_PROFILE_MENU_TOP','MEMBER',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,optional_params,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),'MSM','SUBMENU','{"override":"value","object":"user","field":"username"}',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Submenu','/member-submenu','fa fa-bars fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Submenu','/member-submenu','fa fa-bars fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'ADMAREA','ADMIN',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Admin','/admin','admin_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Administración','/admin','admin_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'MP','PROFILE',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Profile','/member-profile','profile_blue','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Perfil','/member-profile','profile_blue','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'ML','LOGOUT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Log out','/member-logout','logout_blue','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Cerrar sesión','/member-logout','logout_blue','es',true);



-- Admin menu Top
INSERT INTO texts (default_text) VALUES ('Admin Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Admin Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú Admin Top');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('ADMIN_MENU_TOP','ADMIN',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'AD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_TOP'),'Home','/admin','fa fa-home fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_TOP'),'Página de inicio','/admin','fa fa-home fa-1','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'ACR','CHANGEREQUESTS',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CHANGEREQUESTS' and menus.code = 'ADMIN_MENU_TOP'),'Change Requests','/admin-changerequests','cr_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CHANGEREQUESTS' and menus.code = 'ADMIN_MENU_TOP'),'Solicitudes de cambio','/admin-changerequests','cr_green','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'AUM','USERMGMT',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'User Management','/admin-usermgmt','usermgmt_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'Gestión de usuarios','/admin-usermgmt','usermgmt_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AU','USERS',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_TOP'),'Users','/admin-users','users_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_TOP'),'Usuarios','/admin-users','users_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AR','ROLES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_TOP'),'Roles','/admin-roles','users_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_TOP'),'Roles','/admin-roles','users_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AP','PERMISSIONS',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_TOP'),'Permissions','/admin-permissions','key_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_TOP'),'Permisos','/admin-permissions','key_green','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'APR','CONFIGURATION',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'Configuration','/admin-config','fa fa-sliders fa-1','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'Configuración','/admin-config','fa fa-sliders fa-1','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AC','CATEGORY',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_TOP'),'Category','/admin-category','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_TOP'),'Categoría','/admin-category','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AL','LANGUAGE',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_TOP'),'Language','/admin-language','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_TOP'),'Idioma','/admin-language','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AM','MENU',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU' and menus.code = 'ADMIN_MENU_TOP'),'Menu','/admin-menu','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU' and menus.code = 'ADMIN_MENU_TOP'),'Menu','/admin-menu','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'APR','PREFERENCES',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'ADMIN_MENU_TOP'),'Preferences','/admin-prefmgmt','gears_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'ADMIN_MENU_TOP'),'Preferencias','/admin-prefmgmt','gears_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'ASVR','SERVICE',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICE' and menus.code = 'ADMIN_MENU_TOP'),'Service','/admin-service','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICE' and menus.code = 'ADMIN_MENU_TOP'),'Servicio','/admin-service','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AS','STATUS',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_TOP'),'Status','/admin-status','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_TOP'),'Estado','/admin-status','hamburger_green','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'ASM','SUBMENU',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'Other','/admin-other','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'Other','/admin-other','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'SYSAREA','SYSTEM',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_TOP'),'System','/system','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_TOP'),'System','/system','hamburger_green','es',true);


-- System menu Top
INSERT INTO texts (default_text) VALUES ('System menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','System menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','System menu Top');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('SYSTEM_MENU_TOP','ADMIN',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),'SD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'SYSTEM_MENU_TOP'),'Home','/system','home_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'SYSTEM_MENU_TOP'),'Página de inicio','/system','home_green','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),'SSM','SUBMENU',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'Other','/system-other','hamburger_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'Other','/system-other','hamburger_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SCD','CLIENT_DOMAIN',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'SYSTEM_MENU_TOP'),'Client Domain','/system-clientdomain','home_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'SYSTEM_MENU_TOP'),'Dominio del cliente','/system-clientdomain','home_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SSC','SERVICES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'SYSTEM_MENU_TOP'),'Services','/system-services','home_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'SYSTEM_MENU_TOP'),'Servicios','/system-services','home_green','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SA','APPLICATION',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'SYSTEM_MENU_TOP'),'Application','/system-application','home_green','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'SYSTEM_MENU_TOP'),'Solicitud','/system-application','home_green','es',true);



