
-- Public Menu
INSERT INTO texts (default_text) VALUES ('Default Public Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Public Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú pública izquierda');
INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('PUBLIC_MENU_LEFT','PUBLIC',@lastid,'1.0','1.0',null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_HOME','HOME',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_LEFT'),'Home','/index.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_LEFT'),'Casa','/index.html?lang=es','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_ABOUT','ABOUT',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'About','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'Sobre','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_MISSION','MISSION',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MISSION' and menus.code = 'PUBLIC_MENU_LEFT'),'Mission','/page.html?page=mission','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MISSION' and menus.code = 'PUBLIC_MENU_LEFT'),'Misión','/page.html?page=mission&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_FOUNDERS','FOUNDERS',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'FOUNDERS' and menus.code = 'PUBLIC_MENU_LEFT'),'Founders','/page.html?page=founder','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'FOUNDERS' and menus.code = 'PUBLIC_MENU_LEFT'),'Fundadores','/page.html?page=founder&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_DEVELOPERS','DEVELOPERS',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'DEVELOPERS' and menus.code = 'PUBLIC_MENU_LEFT'),'Developers','/page.html?page=developer','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'DEVELOPERS' and menus.code = 'PUBLIC_MENU_LEFT'),'Desarrolladores','/page.html?page=developer&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_LEFT'),'PRM_PUBLIC_MENU_LEFT_APPLICATION','APPLICATION',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'PUBLIC_MENU_LEFT'),'Application','/page.html?page=application','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'PUBLIC_MENU_LEFT'),'Aplicación','/page.html?page=application&lang=es','es',true,null);


INSERT INTO texts (default_text) VALUES ('Default Public Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Public Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú predeterminado a la derecha');
INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('PUBLIC_MENU_RIGHT','PUBLIC',@lastid,'1.0','1.0',null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_SERVICES','SERVICES',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Services','/#services','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Servicios','/#services?lang=es','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_PORTFOLIO','PORTFOLIO',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PORTFOLIO' and menus.code = 'PUBLIC_MENU_RIGHT'),'Portfolio','/#portfolio','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PORTFOLIO' and menus.code = 'PUBLIC_MENU_RIGHT'),'Portafolio','/#portfolio?lang=es','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_ABOUT','ABOUT',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'About','/#about','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'Acerca de','/#about?lang=es','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_TEAM','TEAM',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'TEAM' and menus.code = 'PUBLIC_MENU_RIGHT'),'Team','/#team','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'TEAM' and menus.code = 'PUBLIC_MENU_RIGHT'),'Equipo','/#team?lang=es','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_LOGIN','LOGIN',4,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Login','/login/login.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Iniciar sesión','/login/login.html?lang=es','es',true,null);

INSERT INTO texts (default_text) VALUES ('Default Member Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Member Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Default Menú Menú Derecho');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('MEMBER_MENU_RIGHT','MEMBER',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_ACQUAINTANCES','ACQUAINTANCES',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCES' and menus.code = 'MEMBER_MENU_RIGHT'),'Acquaintances','/member/social/index.html?page=acquaintance','{"iconClass":"fa fa-users"}','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCES' and menus.code = 'MEMBER_MENU_RIGHT'),'Conocidos','/member/social/index.html?page=acquaintance','{"iconClass":"fa fa-users"}','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_EVENTS','EVENTS',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_RIGHT'),'Events','/member/social/index.html?page=events','{"iconClass":"fa fa-calendar"}','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_RIGHT'),'Eventos','/member/social/index.html?page=events','{"iconClass":"fa fa-calendar"}','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_MEMBER','MEMBER',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MEMBER' and menus.code = 'MEMBER_MENU_RIGHT'),'Member','','{"localFile":"/member/img/ed_thumbnail.jpg"}','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MEMBER' and menus.code = 'MEMBER_MENU_RIGHT'),'Miembro','','{"localFile":"/member/img/ed_thumbnail.jpg"}','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'MEMBER' and menus.code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_ADMIN','ADMIN',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_MENU_RIGHT'),'Admin','/admin/index.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_MENU_RIGHT'),'Administración','/admin/index.html','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'MEMBER' and menus.code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_PROFILE','PROFILE',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_MENU_RIGHT'),'Profile','/member/index.html?page=profile','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_MENU_RIGHT'),'Perfil','/member/index.html?page=profile','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'MEMBER' and menus.code = 'MEMBER_MENU_RIGHT'),'PRM_MEMBER_MENU_RIGHT_LOGOUT','LOGOUT',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_MENU_RIGHT'),'Logout','/member/logout.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_MENU_RIGHT'),'Cerrar sesión','/member/logout.html','es',true,null);


-- Private menu
INSERT INTO texts (default_text) VALUES ('Default Member Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Member Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú miembro de Izquierda');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('MEMBER_MENU_LEFT','MEMBER',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_HOME','HOME',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_LEFT'),'Home','/member/social/index.html','en',true,null);

-- Social
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_SOCIAL','SOCIAL',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Social','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Medios de Comunicación Social','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_ACQUAINTANCE','ACQUAINTANCE',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Acquaintances','/member/social/index.html?page=acquaintance','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Conocidos','/member/social/index.html?page=acquaintance&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_GROUPS','GROUPS',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Groups','/member/social/index.html?page=groups','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Grupos','/member/social/index.html?page=groups&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_ACTIVITIES','ACTIVITIES',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Activities','/member/social/index.html?page=activities','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Actividades','/member/social/index.html?page=activities&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_EVENTS','EVENTS',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Events','/member/social/index.html?page=events','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Eventos','/member/social/index.html?page=events&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_MESSAGES','MESSAGES',4,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Messages','/member/social/index.html?page=messages','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Mensajes','/member/social/index.html?page=messages&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'PRM_MEMBER_MENU_LEFT_LIBRARY','LIBRARY',5,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Library','/member/social/index.html?page=library','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Biblioteca','/member/social/index.html?page=library&lang=es','es',true,null);

INSERT INTO texts (default_text) VALUES ('Member Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Member Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú de miembros Arriba');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('MEMBER_MENU_TOP','MEMBER',@lastid,'1.0','1.0',null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_HOME','HOME',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Home','home','home_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Casa','home','home_blue','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_ACQUAINTANCE','ACQUAINTANCE',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Acquaintances','acquaintance','acquaintance_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Conocidos','acquaintance','acquaintance_blue','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_GROUPS','GROUPS',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Groups','groups','groups_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Grupos','groups','groups_blue','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_SHOP','SHOP',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SHOP' and menus.code = 'MEMBER_MENU_TOP'),'Shop','shop','shopping-cart_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SHOP' and menus.code = 'MEMBER_MENU_TOP'),'Tienda','shop','shopping-cart_blue','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_NOTES','NOTES',4,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notes','notes','notes_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notas','notes','notes_blue','es',true,null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'PRM_MEMBER_MENU_TOP_PROFILE','PROFILE',5,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_MENU_TOP'),'Profile','profile','hamburger_blue','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_MENU_TOP'),'Biblioteca','profile','hamburger_blue','es',true,null);

-- Admin menu Right
INSERT INTO texts (default_text) VALUES ('Default Admin Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Admin Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Derecha Admin Menú miembro');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('ADMIN_MENU_RIGHT','ADMIN',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_RIGHT'),'PRM_ADMIN_MENU_RIGHT_ADMIN','ADMIN',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'ADMIN_MENU_RIGHT'),'Admin','','{"localFile":"/member/img/ed_thumbnail.jpg"}','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,image,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'ADMIN_MENU_RIGHT'),'Admin','','{"localFile":"/member/img/ed_thumbnail.jpg"}','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ADMIN' and menus.code = 'ADMIN_MENU_RIGHT'),'PRM_ADMIN_MENU_RIGHT_MEMBER','MEMBER',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MEMBER' and menus.code = 'ADMIN_MENU_RIGHT'),'Member','/member/index.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MEMBER' and menus.code = 'ADMIN_MENU_RIGHT'),'Miembro','/member/index.html','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ADMIN' and menus.code = 'ADMIN_MENU_RIGHT'),'PRM_ADMIN_MENU_RIGHT_PROFILE','PROFILE',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'ADMIN_MENU_RIGHT'),'Profile','/member/index.html?page=profile','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'ADMIN_MENU_RIGHT'),'Perfil','/member/index.html?page=profile','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ADMIN' and menus.code = 'ADMIN_MENU_RIGHT'),'PRM_ADMIN_MENU_RIGHT_LOGOUT','LOGOUT',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'ADMIN_MENU_RIGHT'),'Logout','/admin/logout.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'ADMIN_MENU_RIGHT'),'Cerrar sesión','/admin/logout.html','es',true,null);

-- Admin menu Left
INSERT INTO texts (default_text) VALUES ('Default Admin Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Admin Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menu Admin de Izquierda');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('ADMIN_MENU_LEFT','ADMIN',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_HOME','HOME',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_LEFT'),'Home','/admin/index.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_LEFT'),'Casa','/admin/index.html','es',true,null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_USERMGMT','USERMGMT',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_LEFT'),'User Management','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_LEFT'),'Gestión de usuarios','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_USERS','USERS',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_LEFT'),'Users','/admin/index.html?page=users','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_LEFT'),'Usuarios','/admin/index.html?page=users','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_ROLES','ROLES',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_LEFT'),'Roles','/admin/index.html?page=roles','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_LEFT'),'Roles','/admin/index.html?page=roles','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_PERMISSIONS','PERMISSIONS',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_LEFT'),'Permissions','/admin/index.html?page=permissions','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_LEFT'),'Permisos','/admin/index.html?page=permissions','es',true,null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_SETTINGS','SETTINGS',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'Settings','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'Ajustes','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_PERF_PUBLIC','PREF_PUBLIC',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_PUBLIC' and menus.code = 'ADMIN_MENU_LEFT'),'Page Public','/admin/index.html?page=prefPublic','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_PUBLIC' and menus.code = 'ADMIN_MENU_LEFT'),'Página Público','/admin/index.html?page=prefPublic','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_PREF_MEMBER','PREF_MEMBER',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_MEMBER' and menus.code = 'ADMIN_MENU_LEFT'),'Page Member','/admin/index.html?page=prefMember','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_MEMBER' and menus.code = 'ADMIN_MENU_LEFT'),'Miembro de la página','/admin/index.html?page=prefMember','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_PREF_ADMIN','PREF_ADMIN',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_ADMIN' and menus.code = 'ADMIN_MENU_LEFT'),'Page Admin','/admin/index.html?page=prefAdmin','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREF_ADMIN' and menus.code = 'ADMIN_MENU_LEFT'),'Admin página','/admin/index.html?page=prefAdmin','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_LANGUAGE','LANGUAGE',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_LEFT'),'Language','/admin/index.html?page=language','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_LEFT'),'Idioma','/admin/index.html?page=language','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_CATEGORY','CATEGORY',4,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_LEFT'),'Category','/admin/index.html?page=category','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_LEFT'),'Categoría','/admin/index.html?page=category','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_STATUS','STATUS',5,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_LEFT'),'Status','/admin/index.html?page=status','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_LEFT'),'Estado','/admin/index.html?page=status','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_SERVICE','SERVICE',6,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICE' and menus.code = 'ADMIN_MENU_LEFT'),'Service','/admin/index.html?page=service','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICE' and menus.code = 'ADMIN_MENU_LEFT'),'Servicio','/admin/index.html?page=service','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_MENU_PUBLIC','MENU_PUBLIC',7,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_PUBLIC' and menus.code = 'ADMIN_MENU_LEFT'),'Menu Public','/admin/index.html?page=menuPublic','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_PUBLIC' and menus.code = 'ADMIN_MENU_LEFT'),'Menú público','/admin/index.html?page=menuPublic','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_MENU_MEMBER','MENU_MEMBER',8,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_MEMBER' and menus.code = 'ADMIN_MENU_LEFT'),'Menu Member','/admin/index.html?page=menuMember','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_MEMBER' and menus.code = 'ADMIN_MENU_LEFT'),'Miembro del menú','/admin/index.html?page=menuMember','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SETTINGS' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_MENU_ADMIN','MENU_ADMIN',9,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_ADMIN' and menus.code = 'ADMIN_MENU_LEFT'),'Menu Admin','/admin/index.html?page=menuAdmin','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU_ADMIN' and menus.code = 'ADMIN_MENU_LEFT'),'Menú Admin','/admin/index.html?page=menuAdmin','es',true,null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_SYSTEM','SYSTEM',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_LEFT'),'System','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_LEFT'),'Sistema','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_CLIENT_DOMAIN','CLIENT_DOMAIN',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'ADMIN_MENU_LEFT'),'Client Domain','/admin/index.html?page=clientDomain','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'ADMIN_MENU_LEFT'),'Dominio del cliente','/admin/index.html?page=clientDomain','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_LEFT'),'PRM_ADMIN_MENU_LEFT_APPLICATION','APPLICATION',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'ADMIN_MENU_LEFT'),'Application','/admin/index.html?page=application','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'ADMIN_MENU_LEFT'),'Solicitud','/admin/index.html?page=application','es',true,null);


-- SysAdmin menu Right
INSERT INTO texts (default_text) VALUES ('Default SysAdmin Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default SysAdmin Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Derecha SysAdmin Menú miembro');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('SYSADMIN_MENU_RIGHT','SYSADMIN',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_RIGHT'),'PRM_SYSADMIN_MENU_RIGHT_SYSADMIN','SYSADMIN',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Admin','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Admin','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_RIGHT'),'PRM_SYSADMIN_MENU_RIGHT_PROFILE','PROFILE',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Profile','/sysadmin/index.html?page=profile','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Perfil','/sysadmin/index.html?page=profile','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_RIGHT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_RIGHT'),'PRM_SYSADMIN_MENU_RIGHT_LOGOUT','LOGOUT',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Logout','/sysadmin/logout.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'SYSADMIN_MENU_RIGHT'),'Cerrar sesión','/sysadmin/logout.html','es',true,null);

-- System Admin Left
INSERT INTO texts (default_text) VALUES ('Default SysAdmin Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default SysAdmin Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menu SysAdmin de Izquierda');

INSERT INTO menus (code,category,title_id,api_version,app_version,created) VALUES ('SYSADMIN_MENU_LEFT','SYSADMIN',@lastid,'1.0','1.0',null);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYSADMIN','SYSADMIN',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_LEFT'),'Home','/sysadmin/index.html','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSADMIN' and menus.code = 'SYSADMIN_MENU_LEFT'),'Home','/sysadmin/index.html?lang=es','es',true,null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_CLIENTMGMT','CLIENTMGMT',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENTMGMT' and menus.code = 'SYSADMIN_MENU_LEFT'),'Client Management','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENTMGMT' and menus.code = 'SYSADMIN_MENU_LEFT'),'Client Management','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CLIENTMGMT' and menus.code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYS_CLIENTS','SYS_CLIENTS',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_CLIENTS' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Clients','/sysadmin/index.html?page=clients','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_CLIENTS' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Clients','/sysadmin/index.html?page=clients&lang=es','es',true,null);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_PREFERENCES','PREFERENCES',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'Preferences','','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'Preferences','','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYS_FORMS','SYS_FORMS',0,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_FORMS' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Forms','/sysadmin/index.html?page=forms','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_FORMS' and menus.code = 'SYSADMIN_MENU_LEFT'),'Formas del sistema','/sysadmin/index.html?page=forms&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYS_LABELS','SYS_LABELS',1,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_LABELS' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Labels','/sysadmin/index.html?page=labels','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_LABELS' and menus.code = 'SYSADMIN_MENU_LEFT'),'Las etiquetas del sistema','/sysadmin/index.html?page=labels&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYS_TEXT','SYS_TEXT',2,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_TEXT' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Text','/sysadmin/index.html?page=text','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_TEXT' and menus.code = 'SYSADMIN_MENU_LEFT'),'Texto sistema','/sysadmin/index.html?page=text&lang=es','es',true,null);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order,created) VALUES ((SELECT id FROM menus WHERE code = 'SYSADMIN_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PREFERENCES' and menus.code = 'SYSADMIN_MENU_LEFT'),'PRM_SYSADMIN_MENU_LEFT_SYS_OPTIONS','SYS_OPTIONS',3,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_OPTIONS' and menus.code = 'SYSADMIN_MENU_LEFT'),'System Options','/sysadmin/index.html?page=options','en',true,null);
INSERT INTO menu_item_values (menu_item_id,menu_value,href,lang,rendered,created) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYS_OPTIONS' and menus.code = 'SYSADMIN_MENU_LEFT'),'Opciones del sistema','/sysadmin/index.html?page=options&lang=es','es',true,null);

