
CREATE TABLE `pm_product`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_app` (`name`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_project`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`start_date` datetime NOT NULL,
	`end_date` datetime NOT NULL,
	`product_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_backlog`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`name`,`project_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_release`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`start_date` datetime NOT NULL,
	`end_date` datetime NOT NULL,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`name`,`project_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_sprint`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`start_date` datetime NOT NULL,
	`end_date` datetime NOT NULL,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`release_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`name`,`project_id`),
	UNIQUE KEY `uk_name_rel` (`name`,`release_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`),
	FOREIGN KEY (`release_id`) REFERENCES `pm_release` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_defect`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`summary` varchar(200) NOT NULL,
	`description` text,
	`steps_to_recreate` text,
	`environment` varchar(200),
	`work_around` text,
	`env_users` varchar(200),
	`reported_by_id` bigint(20),
	`assignee_id` bigint(20),
	`severity` varchar(100),
	`priority` int,
	`item_version` varchar(100),
	`external_ref` varchar(100),
	`internal_ref` varchar(100),
	`status` varchar(100),
	`develop_estimate` double(8,2),
	`test_estimate` double(8,2),
	`develop_actual` double(8,2),
	`test_actual` double(8,2),
	`product_id` bigint(20),
	`project_id` bigint(20),
	`release_id` bigint(20),
	`backlog_id` bigint(20),
	`sprint_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`),
	FOREIGN KEY (`release_id`) REFERENCES `pm_release` (`id`),
	FOREIGN KEY (`backlog_id`) REFERENCES `pm_backlog` (`id`),
	FOREIGN KEY (`sprint_id`) REFERENCES `pm_sprint` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;	

CREATE TABLE `pm_enhancement`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`summary` varchar(200) NOT NULL,
	`description` text,
	`reported_by_id` bigint(20),
	`assignee_id` bigint(20),
	`severity` varchar(100),
	`priority` int,
	`item_version` varchar(100),
	`external_ref` varchar(100),
	`internal_ref` varchar(100),
	`status` varchar(100),
	`develop_estimate` double(8,2),
	`test_estimate` double(8,2),
	`develop_duration` double(8,2),
	`test_duration` double(8,2),
	`product_id` bigint(20),
	`project_id` bigint(20),
	`release_id` bigint(20),
	`backlog_id` bigint(20),
	`sprint_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`),
	FOREIGN KEY (`release_id`) REFERENCES `pm_release` (`id`),
	FOREIGN KEY (`backlog_id`) REFERENCES `pm_backlog` (`id`),
	FOREIGN KEY (`sprint_id`) REFERENCES `pm_sprint` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_comment`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`description` text NOT NULL,
	`owner_id` bigint(20),
	`parent_id` bigint(20),
	`defect_id` bigint(20),
	`enhancement_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`parent_id`) REFERENCES `pm_comment` (`id`),
	FOREIGN KEY (`defect_id`) REFERENCES `pm_defect` (`id`),
	FOREIGN KEY (`enhancement_id`) REFERENCES `pm_enhancement` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_scrum`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`name`,`project_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_scrum_request`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`subject` varchar(200) NOT NULL,
	`description` varchar(200),
	`request_days_times` varchar(2000),
	`email_to` varchar(2000),
	`scrum_id` bigint(20) NOT NULL,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_scrum` (`name`,`scrum_id`),
	FOREIGN KEY (`scrum_id`) REFERENCES `pm_scrum` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_scrum_response`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`description` text NOT NULL,
	`scrum_request_id` bigint(20) NOT NULL,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`scrum_request_id`) REFERENCES `pm_scrum_request` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_task`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`summary` varchar(200) NOT NULL,
	`description` text,
	`start_date` datetime NOT NULL,
	`end_date` datetime NOT NULL,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`summary`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`summary`,`project_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_test_scenario`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`summary` varchar(200) NOT NULL,
	`description` text,
	`type` varchar(100) NOT NULL,
	`environment` text,
	`user_info` varchar(2000),
	`setup_info` text,
	`defect_id` bigint(20),
	`enhancement_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_def` (`summary`,`defect_id`),
	UNIQUE KEY `uk_name_enh` (`summary`,`enhancement_id`),
	FOREIGN KEY (`defect_id`) REFERENCES `pm_defect` (`id`),
	FOREIGN KEY (`enhancement_id`) REFERENCES `pm_enhancement` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE `pm_test_case`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`summary` varchar(200) NOT NULL,
	`description` text,
	`environment` text,
	`user_info` varchar(2000),
	`setup_info` text,
	`test_scenario_id` bigint(20) NOT NULL,
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`test_scenario_id`) REFERENCES `pm_test_scenario` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_watcher`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`user_id` bigint(20) NOT NULL,
	`defect_id` bigint(20),
	`enhancement_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`defect_id`) REFERENCES `pm_defect` (`id`),
	FOREIGN KEY (`enhancement_id`) REFERENCES `pm_enhancement` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;


CREATE TABLE `pm_workflow`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`description` text,
	`product_id` bigint(20),
	`project_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_prod` (`name`,`product_id`),
	UNIQUE KEY `uk_name_proj` (`name`,`project_id`),
	FOREIGN KEY (`product_id`) REFERENCES `pm_product` (`id`),
	FOREIGN KEY (`project_id`) REFERENCES `pm_project` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	
CREATE TABLE `pm_workflow_step`
	(`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`name` varchar(200) NOT NULL,
	`workflow_id` bigint(20),
	`workflow_step_id` bigint(20),
	`is_active` bit(1) DEFAULT 1,
	`is_archive` bit(1) DEFAULT 0,
	`is_locked` bit(1) DEFAULT 0,
	`lockowner_id` bigint(20) DEFAULT NULL,
	`modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`lock_time` datetime,
	`version` bigint(20) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`),
	UNIQUE KEY `uk_name_wf` (`name`,`workflow_id`),
	UNIQUE KEY `uk_name_wfs` (`name`,`workflow_step_id`),
	FOREIGN KEY (`workflow_id`) REFERENCES `pm_workflow` (`id`),
	FOREIGN KEY (`workflow_step_id`) REFERENCES `pm_workflow_step` (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_unicode_ci;
	

