
INSERT INTO texts (default_text) VALUES ('Default Public Menu Right');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Public Menu Right');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú predeterminado a la derecha');
INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('PUBLIC_MENU_RIGHT','PUBLIC',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_HOME','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_RIGHT'),'Home','/','/','fa fa-home fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'PUBLIC_MENU_RIGHT'),'Casa','/','/','fa fa-home fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_SERVICES','SERVICES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Services','/services','/services','fa fa-cloud fa-1','earth-grid-select-language-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'PUBLIC_MENU_RIGHT'),'Servicios','/services','/services','fa fa-cloud fa-1','earth-grid-select-language-button','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_ABOUT','ABOUT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'About','/about','/about','fa fa-question-circle fa-1','chat-bubble','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ABOUT' and menus.code = 'PUBLIC_MENU_RIGHT'),'Acerca de','/about','/about','fa fa-question-circle fa-1','chat-bubble','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'PUBLIC_MENU_RIGHT'),'PRM_PUBLIC_MENU_RIGHT_LOGIN','LOGIN',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Login','/login','/login','fa fa-sign-in fa-1','exit-to-app-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGIN' and menus.code = 'PUBLIC_MENU_RIGHT'),'Iniciar sesión','/login','/login','fa fa-sign-in fa-1','exit-to-app-button','es',true);

-- Private menu
INSERT INTO texts (default_text) VALUES ('Default Member Menu Left');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Default Member Menu Left');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú miembro de Izquierda');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_MENU_LEFT','MEMBER',@lastid,'1.0','1.0');
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'MD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_LEFT'),'Home','/member','/member','fa fa-home fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_LEFT'),'Casa','/member','/member','fa fa-home fa-1','home-button','en',true);

-- Social
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),'MS','SOCIAL',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Social','','','','','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'Medios de Comunicación Social','','','','','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSACQUAINTANCE','ACQUAINTANCE',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Acquaintances','/member/acquaintance','/member/acquaintance','fa fa-home fa-1','add-user-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_LEFT'),'Conocidos','/member/acquaintance','/member/acquaintance','fa fa-home fa-1','add-user-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSG','GROUPS',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Groups','/member/groups','/member/groups','fa fa-home fa-1','create-group-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_LEFT'),'Grupos','/member/groups','/member/groups','fa fa-home fa-1','create-group-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSACTIVITY','ACTIVITIES',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Activities','/member/activities','/member/activities','fa fa-home fa-1','create-group-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACTIVITIES' and menus.code = 'MEMBER_MENU_LEFT'),'Actividades','/member/activities','/member/activities','fa fa-home fa-1','create-group-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSEVENTS','EVENTS',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Events','/member/events','/member/events','fa fa-home fa-1','create-group-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EVENTS' and menus.code = 'MEMBER_MENU_LEFT'),'Eventos','/member/events','/member/events','fa fa-home fa-1','create-group-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSMESSAGES','MESSAGES',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Messages','/member/messages','/member/messages','fa fa-home fa-1','create-group-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MESSAGES' and menus.code = 'MEMBER_MENU_LEFT'),'Mensajes','/member/messages','/member/messages','fa fa-home fa-1','create-group-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_LEFT'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SOCIAL' and menus.code = 'MEMBER_MENU_LEFT'),'MSLIBRARY','LIBRARY',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Library','/member/library','/member/library','fa fa-home fa-1','create-group-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LIBRARY' and menus.code = 'MEMBER_MENU_LEFT'),'Biblioteca','/member/library','/member/library','fa fa-home fa-1','create-group-button','es',true);

INSERT INTO texts (default_text) VALUES ('Member Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Member Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú de miembros Arriba');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_MENU_TOP','MEMBER',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Home','/member','/member','fa fa-home fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'MEMBER_MENU_TOP'),'Casa','/member','/member','fa fa-home fa-1','home-button','es',true);

-- PM
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MPM','PM',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'Gate Dog','/pm-gatedog','/pm-gatedog','fa fa-bug fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'Gate Dog','/pm-gatedog','/pm-gatedog','fa fa-bug fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMTEAM','PM_TEAM',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TEAM' and menus.code = 'MEMBER_MENU_TOP'),'Team','/member/pm-team','/member/pm-team','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TEAM' and menus.code = 'MEMBER_MENU_TOP'),'Equipo','/member/pm-team','/member/pm-team','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMPROD','PM_PRODUCT',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PRODUCT' and menus.code = 'MEMBER_MENU_TOP'),'Product','/member/pm-product','/member/pm-product','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PRODUCT' and menus.code = 'MEMBER_MENU_TOP'),'Producto','/member/pm-product','/member/pm-product','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMPROJ','PM_PROJECT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PROJECT' and menus.code = 'MEMBER_MENU_TOP'),'Project','/member/pm-project','/member/pm-project','fa fa-list fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_PROJECT' and menus.code = 'MEMBER_MENU_TOP'),'Proyecto','/memeber/pm-project','/member/pm-project','fa fa-list fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMREL','PM_RELEASE',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_RELEASE' and menus.code = 'MEMBER_MENU_TOP'),'Release','/member/pm-release','/member/pm-release','fa fa-list fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_RELEASE' and menus.code = 'MEMBER_MENU_TOP'),'Lanzamiento','/member/pm-release','/member/pm-release','fa fa-list fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMBAK','PM_BACKLOG',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_BACKLOG' and menus.code = 'MEMBER_MENU_TOP'),'Backlog','/member/pm-backlog','/member/pm-backlog','fa fa-list fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_BACKLOG' and menus.code = 'MEMBER_MENU_TOP'),'Reserva','/member/pm-backlog','/member/pm-backlog','fa fa-list fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMDEF','PM_DEFECT',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEFECT' and menus.code = 'MEMBER_MENU_TOP'),'Defect','/member/pm-defect','/member/pm-defect','fa fa-columns fa-1','bug-report-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEFECT' and menus.code = 'MEMBER_MENU_TOP'),'Defecto','/member/pm-defect','/member/pm-defect','fa fa-columns fa-1','bug-report-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMENH','PM_ENHANCMENT',6);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_ENHANCMENT' and menus.code = 'MEMBER_MENU_TOP'),'Enhancement','/member/pm-enhancement','/member/pm-enhancement','fa fa-list fa-1','puzzle-piece-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_ENHANCMENT' and menus.code = 'MEMBER_MENU_TOP'),'Mejora','/member/pm-enhancement','/member/pm-enhancement','fa fa-list fa-1','puzzle-piece-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMTASK','PM_TASK',7);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TASK' and menus.code = 'MEMBER_MENU_TOP'),'Task','/member/pm-task','/member/pm-task','fa fa-list fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TASK' and menus.code = 'MEMBER_MENU_TOP'),'Tarea','/member/pm-task','/member/pm-task','fa fa-list fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMWF','PM_WORKFLOW',8);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_WORKFLOW' and menus.code = 'MEMBER_MENU_TOP'),'Workflow','/member/pm-workflow','/member/pm-workflow','fa fa-list fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_WORKFLOW' and menus.code = 'MEMBER_MENU_TOP'),'Flujo de trabajo','/member/pm-workflow','/member/pm-workflow','fa fa-list fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMTC','PM_TESTCASE',9);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TESTCASE' and menus.code = 'MEMBER_MENU_TOP'),'Test Case','/member/pm-testcase','/member/pm-testcase','fa-solid fa-microscope thub-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_TESTCASE' and menus.code = 'MEMBER_MENU_TOP'),'Caso de prueba','/member/pm-testcase','/member/pm-testcase','fa-solid fa-microscope thub-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'PM' and menus.code = 'MEMBER_MENU_TOP'),'MPMDEP','PM_DEPLOY',10);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEPLOY' and menus.code = 'MEMBER_MENU_TOP'),'Deploy','/member/pm-deploy','/member/pm-deploy','fa fa-upload fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PM_DEPLOY' and menus.code = 'MEMBER_MENU_TOP'),'Desplegar','/member/pm-deploy','/member/pm-deploy','fa fa-upload fa-1','home-button','es',true);

-- Colony
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MCC','CC',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CC' and menus.code = 'MEMBER_MENU_TOP'),'Hive Watch','/member/cc-dashboard','/member/cc-dashboard','fa fa-bug fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CC' and menus.code = 'MEMBER_MENU_TOP'),'Hive Watch','/member/cc-dashboard','/member/cc-dashboard','fa fa-bug fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CC' and menus.code = 'MEMBER_MENU_TOP'),'MCCO','CC_ORGANIZATION',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CC_ORGANIZATION' and menus.code = 'MEMBER_MENU_TOP'),'Organizations','/member/cc-organization','/member/cc-organization','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CC_ORGANIZATION' and menus.code = 'MEMBER_MENU_TOP'),'Organizaciones','/member/cc-organization','/member/cc-organization','fa fa-columns fa-1','home-button','es',true);

-- Social
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MA','ACQUAINTANCE',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Acquaintances','/member/acquaintances','/member/acquaintances','fa-solid fa-users-group thub-1','two-men','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ACQUAINTANCE' and menus.code = 'MEMBER_MENU_TOP'),'Conocidos','/member/acquaintances','/member/acquaintances','fa-solid fa-users-group thub-1','two-men','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MG','GROUPS',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Groups','/member/groups','/member/groups','fa-solid fa-users-line thub-1','two-men','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'GROUPS' and menus.code = 'MEMBER_MENU_TOP'),'Grupos','/member/groups','/member/groups','fa-solid fa-users-line thub-1','two-men','es',true);
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MN','NOTES',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notes','/member/notes','/member/notes','fa fa-sticky-note fa-1','','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'NOTES' and menus.code = 'MEMBER_MENU_TOP'),'Notas','/member/notes','/member/notes','fa fa-sticky-note fa-1','','es',true);

-- ecommerce
INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),'MEC','EC',6);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'Shop','/ec-shop','/ec-shop','fa fa-cart-arrow-down fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'Tienda','/ec-shop','/ec-shop','fa fa-cart-arrow-down fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'MECMARKET','EC_MARKET',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MARKET' and menus.code = 'MEMBER_MENU_TOP'),'Markets','/member/ec-market','/member/ec-market','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MARKET' and menus.code = 'MEMBER_MENU_TOP'),'Mercados','/member/ec-market','/member/ec-market','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'MECMYSTOREINVENTORY','EC_MYSTOREINV',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREINV' and menus.code = 'MEMBER_MENU_TOP'),'My Store Inventory','/member/ec-mystoreinventory','/member/ec-mystoreinventory','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREINV' and menus.code = 'MEMBER_MENU_TOP'),'Inventario de mi tienda','/member/ec-mystoreinventory','/member/ec-mystoreinventory','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'MECMYSTOREORDERS','EC_MYSTOREORDERS',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREORDERS' and menus.code = 'MEMBER_MENU_TOP'),'My Store Orders','/member/ec-mystoreorders','/member/ec-mystoreorders','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREORDERS' and menus.code = 'MEMBER_MENU_TOP'),'Pedidos de mi tienda','/member/ec-mystoreorders','/member/ec-mystoreorders','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'MECMYSTORERECEIPTS','EC_MYSTORERECEIPTS',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTORERECEIPTS' and menus.code = 'MEMBER_MENU_TOP'),'My Store Receipts','/member/ec-mystorereceipts','/member/ec-mystorereceipts','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTORERECEIPTS' and menus.code = 'MEMBER_MENU_TOP'),'Recibos de mi tienda','/member/ec-mystorereceipts','/member/ec-mystorereceipts','fa fa-columns fa-1','home-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'EC' and menus.code = 'MEMBER_MENU_TOP'),'MECMYSTOREEMPLOYEES','EC_MYSTOREEMPLOYEES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREEMPLOYEES' and menus.code = 'MEMBER_MENU_TOP'),'My Store Employees','/member/ec-mystoreemployees','/member/ec-mystoreemployees','fa fa-columns fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'EC_MYSTOREEMPLOYEES' and menus.code = 'MEMBER_MENU_TOP'),'Empleados de mi tienda','/member/ec-mystoreemployees','/member/ec-mystoreemployees','fa fa-columns fa-1','home-button','es',true);


-- user profile
INSERT INTO texts (default_text) VALUES ('Member Profile Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Member Profile Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Parte superior del menú de perfil de miembro');
INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('MEMBER_PROFILE_MENU_TOP','MEMBER',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,optional_params,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),'MSM','SUBMENU','{"override":"value","object":"user","field":"username"}',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Submenu','/member-submenu','/member-submenu','fa fa-bars fa-1','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Submenu','/member-submenu','/member-submenu','fa fa-bars fa-1','menu-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'ADMAREA','ADMIN',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Admin','/admin','/admin','admin_green','car-front','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ADMIN' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Administración','/admin','/admin','admin_green','car-front','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'MP','PROFILE',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Profile','/member/profile','/member/profile','profile_blue','framed-portrait','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PROFILE' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Perfil','/member/profile','/member/profile','profile_blue','framed-portrait','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'MEMBER_PROFILE_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'ML','LOGOUT',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Log out','/member/logout','/member/logout','logout_blue','exit-to-app-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LOGOUT' and menus.code = 'MEMBER_PROFILE_MENU_TOP'),'Cerrar sesión','/member/logout','/member/logout','logout_blue','exit-to-app-button','es',true);



-- Admin menu Top
INSERT INTO texts (default_text) VALUES ('Admin Menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','Admin Menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','Menú Admin Top');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('ADMIN_MENU_TOP','ADMIN',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'AD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_TOP'),'Home','/admin','/admin','fa fa-home fa-1','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'ADMIN_MENU_TOP'),'Página de inicio','/admin','/admin','fa fa-home fa-1','home-button','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'ACR','CHANGEREQUESTS',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CHANGEREQUESTS' and menus.code = 'ADMIN_MENU_TOP'),'Change Requests','/admin/changerequests','/admin/changerequests','cr_green','home-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CHANGEREQUESTS' and menus.code = 'ADMIN_MENU_TOP'),'Solicitudes de cambio','/admin/changerequests','/admin/changerequests','cr_green','home-button','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'AEC','ECOMMERCE',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ECOMMERCE' and menus.code = 'ADMIN_MENU_TOP'),'Ecommerce','/admin/ecommerce','/admin/ecommerce','usermgmt_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ECOMMERCE' and menus.code = 'ADMIN_MENU_TOP'),'Gestión de usuarios','/admin/ecommerce','/admin/ecommerce','usermgmt_green','menu-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ECOMMERCE' and menus.code = 'ADMIN_MENU_TOP'),'AECMARKET','MARKETS',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MARKETS' and menus.code = 'ADMIN_MENU_TOP'),'Markets','/admin/ec-markets','/admin/ec-markets','users_green','two-men','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MARKETS' and menus.code = 'ADMIN_MENU_TOP'),'Mercados','/admin/ec-markets','/admin/ec-markets','users_green','two-men','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'ECOMMERCE' and menus.code = 'ADMIN_MENU_TOP'),'AECSTORE','STORES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STORES' and menus.code = 'ADMIN_MENU_TOP'),'Stores','/admin/ec-stores','/admin/ec-stores','users_green','round-account-button-with-user-inside','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STORES' and menus.code = 'ADMIN_MENU_TOP'),'Historias','/admin/ec-stores','/admin/ec-stores','users_green','round-account-button-with-user-inside','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'AUM','USERMGMT',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'User Management','/admin/usermgmt','/admin/usermgmt','usermgmt_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'Gestión de usuarios','/admin/usermgmt','/admin/usermgmt','usermgmt_green','menu-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AU','USERS',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_TOP'),'Users','/admin/users','/admin/users','users_green','two-men','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'USERS' and menus.code = 'ADMIN_MENU_TOP'),'Usuarios','/admin/users','/admin/users','users_green','two-men','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AR','ROLES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_TOP'),'Roles','/admin/roles','/admin/roles','users_green','round-account-button-with-user-inside','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'ROLES' and menus.code = 'ADMIN_MENU_TOP'),'Roles','/admin/roles','/admin/roles','users_green','round-account-button-with-user-inside','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'USERMGMT' and menus.code = 'ADMIN_MENU_TOP'),'AP','PERMISSIONS',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_TOP'),'Permissions','/admin/permissions','/admin/permissions','key_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PERMISSIONS' and menus.code = 'ADMIN_MENU_TOP'),'Permisos','/admin/permissions','/admin/permissions','key_green','settings-cogwheel-button','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'APR','CONFIGURATION',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'Configuration','/admin/config','/admin/config','fa fa-sliders fa-1','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'Configuración','/admin/config','/admin/config','fa fa-sliders fa-1','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AC','CATEGORY',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_TOP'),'Category','/admin/category','/admin/category','hamburger_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CATEGORY' and menus.code = 'ADMIN_MENU_TOP'),'Categoría','/admin/category','/admin/category','hamburger_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AL','LANGUAGE',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_TOP'),'Language','/admin/language','/admin/language','hamburger_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'LANGUAGE' and menus.code = 'ADMIN_MENU_TOP'),'Idioma','/admin/language','/admin/language','hamburger_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AM','MENU',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU' and menus.code = 'ADMIN_MENU_TOP'),'Menu','/admin/menu','/admin/menu','hamburger_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'MENU' and menus.code = 'ADMIN_MENU_TOP'),'Menu','/admin/menu','/admin/menu','hamburger_green','menu-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'APR','PREFERENCES',3);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'ADMIN_MENU_TOP'),'Preferences','/admin/prefmgmt','/admin/prefmgmt','gears_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'PREFERENCES' and menus.code = 'ADMIN_MENU_TOP'),'Preferencias','/admin/prefmgmt','/admin/prefmgmt','gears_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'CONFIGURATION' and menus.code = 'ADMIN_MENU_TOP'),'AS','STATUS',4);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_TOP'),'Status','/admin/status','/admin/status','hamburger_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'STATUS' and menus.code = 'ADMIN_MENU_TOP'),'Estado','/admin/status','/admin/status','hamburger_green','menu-button','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),'ASM','SUBMENU',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'Other','/admin/other','/admin/other','hamburger_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'Other','/admin/other','/admin/other','hamburger_green','menu-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'ADMIN_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'ADMIN_MENU_TOP'),'SYSAREA','SYSTEM',5);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_TOP'),'System','/system','/system','hamburger_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SYSTEM' and menus.code = 'ADMIN_MENU_TOP'),'System','/system','/system','hamburger_green','settings-cogwheel-button','es',true);


-- System menu Top
INSERT INTO texts (default_text) VALUES ('System menu Top');
SET @lastid = LAST_INSERT_ID();
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'en','System menu Top');
INSERT INTO langtexts (text_id,lang,text) VALUES (@lastid,'es','System menu Top');

INSERT INTO menus (code,category,title_id,api_version,app_version) VALUES ('SYSTEM_MENU_TOP','ADMIN',@lastid,'1.0','1.0');

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),'SD','HOME',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'SYSTEM_MENU_TOP'),'Home','/system','/system','home_green','menu-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'HOME' and menus.code = 'SYSTEM_MENU_TOP'),'Página de inicio','/system','/system','home_green','menu-button','es',true);

INSERT INTO menu_items (menu_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),'SSM','SUBMENU',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'Other','/system/other','/system/other','hamburger_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'Other','/system/other','/system/other','hamburger_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SCD','CLIENT_DOMAIN',0);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'SYSTEM_MENU_TOP'),'Client Domain','/system/clientdomain','/system/clientdomain','home_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'CLIENT_DOMAIN' and menus.code = 'SYSTEM_MENU_TOP'),'Dominio del cliente','/system/clientdomain','/system/clientdomain','home_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SSC','SERVICES',1);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'SYSTEM_MENU_TOP'),'Services','/system/services','/system/services','home_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'SERVICES' and menus.code = 'SYSTEM_MENU_TOP'),'Servicios','/system/services','/system/services','home_green','settings-cogwheel-button','es',true);
INSERT INTO menu_items (menu_id,parent_id,permission_code,code,sort_order) VALUES ((SELECT id FROM menus WHERE code = 'SYSTEM_MENU_TOP'),(SELECT item.id FROM menu_items AS item JOIN menus ON item.menu_id = menus.id WHERE item.code = 'SUBMENU' and menus.code = 'SYSTEM_MENU_TOP'),'SA','APPLICATION',2);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'SYSTEM_MENU_TOP'),'Application','/system/application','/system/application','home_green','settings-cogwheel-button','en',true);
INSERT INTO menu_item_values (menu_item_id,menu_value,route_web,route_native,icon_web,icon_native,lang,rendered) VALUES ((SELECT menu_items.id FROM menu_items JOIN menus on menu_items.menu_id = menus.id WHERE menu_items.code = 'APPLICATION' and menus.code = 'SYSTEM_MENU_TOP'),'Solicitud','/system/application','/system/application','home_green','settings-cogwheel-button','es',true);

